language: node_js
dist: trusty
node_js: '6'
sudo: required
install:
- sudo apt-get install git screen
- npm install -g selenium-standalone
- npm install -g phantomjs-prebuilt
- npm install -g nightwatch
- npm install
- selenium-standalone install
before_script:
- screen -dm selenium-standalone start
- screen -dm npm start
- sleep 60
script:
- curl -I http://localhost:3000/
before_deploy:
  - mv static/crawled/ /tmp/crawled/
  - openssl des3 -d -in pitskulounas.crypted -out /tmp/deploy_key -k $PRIVATE_KEY_PASSWORD;
  - chmod 0600 /tmp/deploy_key
  - eval `ssh-agent -s`
  - ssh-add /tmp/deploy_key
deploy: 
  skip_cleanup: true
  provider: script
  script: travis_deploy.sh
  on:
    branch: master
after_deploy:
  - shred /tmp/deploy_key
